name: dwb
description: The Dart web browser.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0-180.3.beta

dependencies:
  dio: ^5.4.3+1
  html: ^0.15.4
  mason_logger: ^0.2.15

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
